### ISSUE TITLE
节点管理，怎么添加节点信息？

### ISSUE THREAD

**Issue by devhh** [JoeyBling/webkettle#7]

**Comment by JoeyBling** [comment]
是**pdi**提供的一个web服务
> 用来远程调用执行任务或转换。

**Comment by devhh** [comment]
你好，请问下若服务器只运行一个web服务，节点信息的端口（是否服务发布端口），web app name, 用户名，密码信息在哪里获取？如下图：
![image](https://user-images.githubusercontent.com/16056879/62044997-cd120880-b236-11e9-93d0-4ce72879d7a0.png)
